version: '3'
services:
  clasp:
    build:
      context: ./gas
      dockerfile: Dockerfile
    volumes:
      - ./gas:/code
      - /code/node_modules
    ports:
      - '3030:3030'
    command: tail -f /dev/null